# Site settings
title: dragerace
email: 240300675@ucaribe.edu.mx
description: > 
baseurl: "" # un elemento/blog/
url: "" # dragerace.me 

twitter_username: juianche07
github_username: Emilianoucaribe07

# Build settings
markdown: kramdown
